### ISSUE TITLE
How do you start using this project?

### ISSUE THREAD

**Issue by rococtz** [T-G-P/MetalAPI#4]
Hi,

I have looked at your project, but it's not very clear for me. How do you use it? Do I need to scrape everything myself? Do I host the API server, but I use your data? Or do you host everything I can access a public API that you expose? 

Thanks

**Comment by tobocop2** [comment]
Hey, the API is down. Due to work, i just haven't had time to rebuild 
it. I will keep you posted. You can try scraping it with my scraper, and 
then you'll have all the data assuming that still works. If you just 
want the data, that is the way to go for now. If you want a web API, I 
don't plan to stand up that server until I rebuild the entire thing from 
scratch...which hopefully is sooner than later.

Sorry,

Tobias

**Comment by rococtz** [comment]
Thank you for the info!
